In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("hotel_bookings.csv")

In [3]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [4]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [5]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [6]:
df.shape

(119390, 32)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [8]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [9]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [10]:
df["company"]

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
119385   NaN
119386   NaN
119387   NaN
119388   NaN
119389   NaN
Name: company, Length: 119390, dtype: float64

In [11]:
df.drop("company",axis=1,inplace=True)
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,3,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,4,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,No Deposit,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,No Deposit,304.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,0,No Deposit,394.0,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,0,No Deposit,9.0,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,0,No Deposit,9.0,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,0,No Deposit,89.0,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,0,No Deposit,9.0,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [12]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [13]:
df.shape

(119390, 31)

In [14]:
df["agent"].unique()

array([ nan, 304., 240., 303.,  15., 241.,   8., 250., 115.,   5., 175.,
       134., 156., 243., 242.,   3., 105.,  40., 147., 306., 184.,  96.,
         2., 127.,  95., 146.,   9., 177.,   6., 143., 244., 149., 167.,
       300., 171., 305.,  67., 196., 152., 142., 261., 104.,  36.,  26.,
        29., 258., 110.,  71., 181.,  88., 251., 275.,  69., 248., 208.,
       256., 314., 126., 281., 273., 253., 185., 330., 334., 328., 326.,
       321., 324., 313.,  38., 155.,  68., 335., 308., 332.,  94., 348.,
       310., 339., 375.,  66., 327., 387., 298.,  91., 245., 385., 257.,
       393., 168., 405., 249., 315.,  75., 128., 307.,  11., 436.,   1.,
       201., 183., 223., 368., 336., 291., 464., 411., 481.,  10., 154.,
       468., 410., 390., 440., 495., 492., 493., 434.,  57., 531., 420.,
       483., 526., 472., 429.,  16., 446.,  34.,  78., 139., 252., 270.,
        47., 114., 301., 193., 182., 135., 350., 195., 352., 355., 159.,
       363., 384., 360., 331., 367.,  64., 406., 163., 414., 333., 427.,
       431., 430., 426., 438., 433., 418., 441., 282., 432.,  72., 450.,
       180., 454., 455.,  59., 451., 254., 358., 469., 165., 467., 510.,
       337., 476., 502., 527., 479., 508., 535., 302., 497., 187.,  13.,
         7.,  27.,  14.,  22.,  17.,  28.,  42.,  20.,  19.,  45.,  37.,
        61.,  39.,  21.,  24.,  41.,  50.,  30.,  54.,  52.,  12.,  44.,
        31.,  83.,  32.,  63.,  60.,  55.,  56.,  89.,  87., 118.,  86.,
        85., 210., 214., 129., 179., 138., 174., 170., 153.,  93., 151.,
       119.,  35., 173.,  58.,  53., 133.,  79., 235., 192., 191., 236.,
       162., 215., 157., 287., 132., 234.,  98.,  77., 103., 107., 262.,
       220., 121., 205., 378.,  23., 296., 290., 229.,  33., 286., 276.,
       425., 484., 323., 403., 219., 394., 509., 111., 423.,   4.,  70.,
        82.,  81.,  74.,  92.,  99.,  90., 112., 117., 106., 148., 158.,
       144., 211., 213., 216., 232., 150., 267., 227., 247., 278., 280.,
       285., 289., 269., 295., 265., 288., 122., 294., 325., 341., 344.,
       346., 359., 283., 364., 370., 371.,  25., 141., 391., 397., 416.,
       404., 299., 197.,  73., 354., 444., 408., 461., 388., 453., 459.,
       474., 475., 480., 449.])

In [15]:
df["deposit_type"].unique()

array(['No Deposit', 'Refundable', 'Non Refund'], dtype=object)

In [16]:
month_map = {
    'January': 1,
    'February': 2,
    'March': 3,
    'April': 4,
    'May': 5,
    'June': 6,
    'July': 7,
    'August': 8,
    'September': 9,
    'October': 10,
    'November': 11,
    'December': 12
}

# Convert 'arrival_date_month' column to numeric representation
df['arrival_date_month'] = df['arrival_date_month'].map(month_map)

# Check the modified DataFrame
print(df)

               hotel  is_canceled  lead_time  arrival_date_year  \
0       Resort Hotel            0        342               2015
1       Resort Hotel            0        737               2015
2       Resort Hotel            0          7               2015
3       Resort Hotel            0         13               2015
4       Resort Hotel            0         14               2015
...              ...          ...        ...                ...
119385    City Hotel            0         23               2017
119386    City Hotel            0        102               2017
119387    City Hotel            0         34               2017
119388    City Hotel            0        109               2017
119389    City Hotel            0        205               2017

        arrival_date_month  arrival_date_week_number  \
0                        7                        27
1                        7                        27
2                        7                        27
3                        7                        27
4                        7                        27
...                    ...                       ...
119385                   8                        35
119386                   8                        35
119387                   8                        35
119388                   8                        35
119389                   8                        35

        arrival_date_day_of_month  stays_in_weekend_nights  \
0                               1                        0
1                               1                        0
2                               1                        0
3                               1                        0
4                               1                        0
...                           ...                      ...
119385                         30                        2
119386                         31                        2
119387                         31                        2
119388                         31                        2
119389                         29                        2

        stays_in_week_nights  adults  ...  booking_changes  deposit_type  \
0                          0       2  ...                3    No Deposit
1                          0       2  ...                4    No Deposit
2                          1       1  ...                0    No Deposit
3                          1       1  ...                0    No Deposit
4                          2       2  ...                0    No Deposit
...                      ...     ...  ...              ...           ...
119385                     5       2  ...                0    No Deposit
119386                     5       3  ...                0    No Deposit
119387                     5       2  ...                0    No Deposit
119388                     5       2  ...                0    No Deposit
119389                     7       2  ...                0    No Deposit

        agent days_in_waiting_list customer_type     adr  \
0         NaN                    0     Transient    0.00
1         NaN                    0     Transient    0.00
2         NaN                    0     Transient   75.00
3       304.0                    0     Transient   75.00
4       240.0                    0     Transient   98.00
...       ...                  ...           ...     ...
119385  394.0                    0     Transient   96.14
119386    9.0                    0     Transient  225.43
119387    9.0                    0     Transient  157.71
119388   89.0                    0     Transient  104.40
119389    9.0                    0     Transient  151.20

        required_car_parking_spaces  total_of_special_requests  \
0                                 0                          0
1                                 0                          0
2                                 0                          0
3                                 0                          0
4                                 0                          1
...                             ...                        ...
119385                            0                          0
119386                            0                          2
119387                            0                          4
119388                            0                          0
119389                            0                          2

        reservation_status reservation_status_date
0                Check-Out              2015-07-01
1                Check-Out              2015-07-01
2                Check-Out              2015-07-02
3                Check-Out              2015-07-02
4                Check-Out              2015-07-03
...                    ...                     ...
119385           Check-Out              2017-09-06
119386           Check-Out              2017-09-07
119387           Check-Out              2017-09-07
119388           Check-Out              2017-09-07
119389           Check-Out              2017-09-07

[119390 rows x 31 columns]

In [17]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [18]:
df["arrival_date_day_of_month"]

0          1
1          1
2          1
3          1
4          1
          ..
119385    30
119386    31
119387    31
119388    31
119389    29
Name: arrival_date_day_of_month, Length: 119390, dtype: int64

In [19]:
df['arrival_date'] = pd.to_datetime(df['arrival_date_year'].astype(str) + '-' +
                                    df['arrival_date_month'].astype(str) + '-' +
                                    df['arrival_date_day_of_month'].astype(str))

In [20]:
df.drop(columns=['arrival_date_year', 'arrival_date_month', 'arrival_date_day_of_month'], inplace=True)

In [21]:
df

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,...,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,2015-07-01
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,...,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,2015-07-01
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,...,No Deposit,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,...,No Deposit,304.0,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,...,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03,2015-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2,5,2,0.0,0,BB,...,No Deposit,394.0,0,Transient,96.14,0,0,Check-Out,2017-09-06,2017-08-30
119386,City Hotel,0,102,35,2,5,3,0.0,0,BB,...,No Deposit,9.0,0,Transient,225.43,0,2,Check-Out,2017-09-07,2017-08-31
119387,City Hotel,0,34,35,2,5,2,0.0,0,BB,...,No Deposit,9.0,0,Transient,157.71,0,4,Check-Out,2017-09-07,2017-08-31
119388,City Hotel,0,109,35,2,5,2,0.0,0,BB,...,No Deposit,89.0,0,Transient,104.40,0,0,Check-Out,2017-09-07,2017-08-31
119389,City Hotel,0,205,35,2,7,2,0.0,0,HB,...,No Deposit,9.0,0,Transient,151.20,0,2,Check-Out,2017-09-07,2017-08-29

In [22]:
df.drop('arrival_date_week_number',axis=1,inplace=True)

In [23]:
df

,hotel,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date
0,Resort Hotel,0,342,0,0,2,0.0,0,BB,PRT,...,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,2015-07-01
1,Resort Hotel,0,737,0,0,2,0.0,0,BB,PRT,...,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,2015-07-01
2,Resort Hotel,0,7,0,1,1,0.0,0,BB,GBR,...,No Deposit,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01
3,Resort Hotel,0,13,0,1,1,0.0,0,BB,GBR,...,No Deposit,304.0,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01
4,Resort Hotel,0,14,0,2,2,0.0,0,BB,GBR,...,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03,2015-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2,5,2,0.0,0,BB,BEL,...,No Deposit,394.0,0,Transient,96.14,0,0,Check-Out,2017-09-06,2017-08-30
119386,City Hotel,0,102,2,5,3,0.0,0,BB,FRA,...,No Deposit,9.0,0,Transient,225.43,0,2,Check-Out,2017-09-07,2017-08-31
119387,City Hotel,0,34,2,5,2,0.0,0,BB,DEU,...,No Deposit,9.0,0,Transient,157.71,0,4,Check-Out,2017-09-07,2017-08-31
119388,City Hotel,0,109,2,5,2,0.0,0,BB,GBR,...,No Deposit,89.0,0,Transient,104.40,0,0,Check-Out,2017-09-07,2017-08-31
119389,City Hotel,0,205,2,7,2,0.0,0,HB,DEU,...,No Deposit,9.0,0,Transient,151.20,0,2,Check-Out,2017-09-07,2017-08-29

In [24]:
df["agent"].isnull().sum()

16340

In [25]:
df.corr()["is_canceled"]

C:\Users\chitr\AppData\Local\Temp\ipykernel_23660\1590657574.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()["is_canceled"]

is_canceled                       1.000000
lead_time                         0.293123
stays_in_weekend_nights          -0.001791
stays_in_week_nights              0.024765
adults                            0.060017
children                          0.005048
babies                           -0.032491
is_repeated_guest                -0.084793
previous_cancellations            0.110133
previous_bookings_not_canceled   -0.057358
booking_changes                  -0.144381
agent                            -0.083114
days_in_waiting_list              0.054186
adr                               0.047557
required_car_parking_spaces      -0.195498
total_of_special_requests        -0.234658
Name: is_canceled, dtype: float64

In [26]:
df.dropna(subset="agent",axis=0,inplace=True)
df.shape

(103050, 28)

In [27]:
df.head(60)

,hotel,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date
3,Resort Hotel,0,13,0,1,1,0.0,0,BB,GBR,...,No Deposit,304.0,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01
4,Resort Hotel,0,14,0,2,2,0.0,0,BB,GBR,...,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03,2015-07-01
5,Resort Hotel,0,14,0,2,2,0.0,0,BB,GBR,...,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03,2015-07-01
7,Resort Hotel,0,9,0,2,2,0.0,0,FB,PRT,...,No Deposit,303.0,0,Transient,103.00,0,1,Check-Out,2015-07-03,2015-07-01
8,Resort Hotel,1,85,0,3,2,0.0,0,BB,PRT,...,No Deposit,240.0,0,Transient,82.00,0,1,Canceled,2015-05-06,2015-07-01
9,Resort Hotel,1,75,0,3,2,0.0,0,HB,PRT,...,No Deposit,15.0,0,Transient,105.50,0,0,Canceled,2015-04-22,2015-07-01
10,Resort Hotel,1,23,0,4,2,0.0,0,BB,PRT,...,No Deposit,240.0,0,Transient,123.00,0,0,Canceled,2015-06-23,2015-07-01
11,Resort Hotel,0,35,0,4,2,0.0,0,HB,PRT,...,No Deposit,240.0,0,Transient,145.00,0,0,Check-Out,2015-07-05,2015-07-01
12,Resort Hotel,0,68,0,4,2,0.0,0,BB,USA,...,No Deposit,240.0,0,Transient,97.00,0,3,Check-Out,2015-07-05,2015-07-01
13,Resort Hotel,0,18,0,4,2,1.0,0,HB,ESP,...,No Deposit,241.0,0,Transient,154.77,0,1,Check-Out,2015-07-05,2015-07-01
14,Resort Hotel,0,37,0,4,2,0.0,0,BB,PRT,...,No Deposit,241.0,0,Transient,94.71,0,0,Check-Out,2015-07-05,2015-07-01
15,Resort Hotel,0,68,0,4,2,0.0,0,BB,IRL,...,No Deposit,240.0,0,Transient,97.00,0,3,Check-Out,2015-07-05,2015-07-01
16,Resort Hotel,0,37,0,4,2,0.0,0,BB,PRT,...,No Deposit,8.0,0,Contract,97.50,0,0,Check-Out,2015-07-05,2015-07-01
17,Resort Hotel,0,12,0,1,2,0.0,0,BB,IRL,...,No Deposit,240.0,0,Transient,88.20,0,0,Check-Out,2015-07-02,2015-07-01
19,Resort Hotel,0,7,0,4,2,0.0,0,BB,GBR,...,No Deposit,250.0,0,Transient,153.00,0,1,Check-Out,2015-07-05,2015-07-01
20,Resort Hotel,0,37,1,4,1,0.0,0,BB,GBR,...,No Deposit,241.0,0,Transient,97.29,0,1,Check-Out,2015-07-06,2015-07-01
21,Resort Hotel,0,72,2,4,2,0.0,0,BB,PRT,...,No Deposit,250.0,0,Transient,84.67,0,1,Check-Out,2015-07-07,2015-07-01
22,Resort Hotel,0,72,2,4,2,0.0,0,BB,PRT,...,No Deposit,250.0,0,Transient,84.67,0,1,Check-Out,2015-07-07,2015-07-01
23,Resort Hotel,0,72,2,4,2,0.0,0,BB,PRT,...,No Deposit,250.0,0,Transient,99.67,0,1,Check-Out,2015-07-07,2015-07-01
24,Resort Hotel,0,127,2,5,2,0.0,0,HB,GBR,...,No Deposit,115.0,0,Contract,94.95,0,1,Check-Out,2015-07-01,2015-07-01
25,Resort Hotel,0,78,2,5,2,0.0,0,BB,PRT,...,No Deposit,5.0,0,Transient,63.60,1,0,Check-Out,2015-07-08,2015-07-01
26,Resort Hotel,0,48,2,5,2,0.0,0,BB,IRL,...,No Deposit,8.0,0,Contract,79.50,0,0,Check-Out,2015-07-08,2015-07-01
27,Resort Hotel,1,60,2,5,2,0.0,0,BB,PRT,...,No Deposit,240.0,0,Transient,107.00,0,2,Canceled,2015-05-11,2015-07-01
28,Resort Hotel,0,77,2,5,2,0.0,0,BB,PRT,...,No Deposit,240.0,0,Transient,94.00,0,0,Check-Out,2015-07-08,2015-07-01
29,Resort Hotel,0,99,2,5,2,0.0,0,BB,PRT,...,No Deposit,240.0,0,Transient,87.30,1,1,Check-Out,2015-07-08,2015-07-01
31,Resort Hotel,0,95,4,11,2,0.0,0,BB,GBR,...,No Deposit,241.0,0,Transient,63.86,0,0,Check-Out,2015-07-16,2015-07-01
33,Resort Hotel,0,69,2,4,2,0.0,0,BB,IRL,...,No Deposit,175.0,0,Transient,65.50,0,0,Check-Out,2015-07-08,2015-07-02
34,Resort Hotel,1,45,1,3,3,0.0,0,BB,PRT,...,No Deposit,241.0,0,Transient,108.80,0,1,Canceled,2015-05-19,2015-07-02
35,Resort Hotel,1,40,1,3,3,0.0,0,BB,PRT,...,No Deposit,241.0,0,Transient,108.80,0,1,Canceled,2015-06-19,2015-07-02
36,Resort Hotel,0,15,1,3,2,0.0,0,BB,ESP,...,No Deposit,240.0,0,Transient,98.00,0,0,Check-Out,2015-07-06,2015-07-02
37,Resort Hotel,0,36,1,3,3,0.0,0,BB,PRT,...,No Deposit,241.0,0,Transient,108.80,0,1,Check-Out,2015-07-06,2015-07-02
38,Resort Hotel,1,43,1,3,3,0.0,0,BB,PRT,...,No Deposit,241.0,0,Transient,108.80,0,0,Canceled,2015-05-23,2015-07-02
39,Resort Hotel,0,70,2,3,2,0.0,0,HB,ROU,...,No Deposit,250.0,0,Transient,137.00,0,1,Check-Out,2015-07-07,2015-07-02
40,Resort Hotel,1,45,2,3,2,0.0,0,BB,PRT,...,No Deposit,241.0,0,Transient,117.81,0,0,Canceled,2015-05-18,2015-07-02
41,Resort Hotel,0,45,2,3,2,0.0,0,BB,IRL,...,No Deposit,8.0,0,Contract,79.50,0,0,Check-Out,2015-07-07,2015-07-02
43,Resort Hotel,0,70,2,3,2,0.0,0,HB,ROU,...,No Deposit,250.0,0,Transient,137.00,0,1,Check-Out,2015-07-07,2015-07-02
44,Resort Hotel,0,107,2,5,2,0.0,0,BB,PRT,...,No Deposit,240.0,0,Transient,110.70,0,2,Check-Out,2015-07-09,2015-07-02
45,Resort Hotel,1,47,2,5,2,2.0,0,BB,PRT,...,No Deposit,240.0,0,Transient,153.00,0,0,Canceled,2015-06-02,2015-07-02
46,Resort Hotel,0,96,2,5,2,0.0,0,BB,ESP,...,No Deposit,134.0,0,Transient,58.95,0,1,Check-Out,2015-07-09,2015-07-02
47,Resort Hotel,0,113,2,5,2,0.0,0,BB,NOR,...,No Deposit,156.0,0,Transient-Party,82.88,0,2,Check-Out,2015-07-09,2015-07-02
48,Resort Hotel,0,90,2,5,2,0.0,0,HB,GBR,...,No Deposit,243.0,0,Contract,82.35,0,0,Check-Out,2015-07-09,2015-07-02
49,Resort Hotel,0,50,2,5,2,0.0,0,HB,IRL,...,No Deposit,241.0,0,Transient,119.35,0,1,Check-Out,2015-07-09,2015-07-02
50,Resort Hotel,0,113,2,5,2,0.0,0,BB,NOR,...,No Deposit,156.0,0,Transient-Party,67.58,0,2,Check-Out,2015-07-09,2015-07-02
51,Resort Hotel,0,93,3,8,2,0.0,0,BB,IRL,...,No Deposit,156.0,0,Contract,56.01,0,0,Check-Out,2015-07-13,2015-07-02
52,Resort Hotel,0,76,4,10,2,0.0,0,BB,OMN,...,No Deposit,243.0,0,Contract,110.70,0,0,Check-Out,2015-07-16,2015-07-02
53,Resort Hotel,0,3,0,1,2,0.0,0,BB,ESP,...,No Deposit,240.0,0,Transient,88.20,1,0,Check-Out,2015-07-03,2015-07-02
54,Resort Hotel,0,1,0,1,2,0.0,0,BB,ARG,...,No Deposit,240.0,0,Transient,147.00,1,0,Check-Out,2015-07-03,2015-07-02
57,Resort Hotel,0,0,0,1,2,0.0,0,BB,PRT,...,No Deposit,240.0,0,Transient,117.90,0,2,Check-Out,2015-07-03,2015-07-02
59,Resort Hotel,0,14,0,2,2,0.0,0,BB,USA,...,No Deposit,242.0,0,Transient,98.00,0,1,Check-Out,2015-07-04,2015-07-02
60,Resort Hotel,0,10,0,2,2,0.0,0,BB,PRT,...,No Deposit,241.0,0,Transient,117.81,0,0,Check-Out,2015-07-04,2015-07-02
61,Resort Hotel,0,5,0,2,2,0.0,0,BB,IRL,...,No Deposit,240.0,0,Transient,135.00,1,2,Check-Out,2015-07-04,2015-07-02
62,Resort Hotel,0,17,0,3,2,0.0,0,BB,ESP,...,No Deposit,250.0,0,Transient,133.00,0,1,Check-Out,2015-07-05,2015-07-02
63,Resort Hotel,0,93,0,3,2,0.0,0,BB,IRL,...,No Deposit,115.0,0,Contract,58.95,0,0,Check-Out,2015-07-05,2015-07-02
64,Resort Hotel,1,3,0,3,2,0.0,0,HB,PRT,...,No Deposit,240.0,0,Transient,136.33,0,2,Canceled,2015-06-29,2015-07-02
65,Resort Hotel,0,10,0,2,2,2.0,0,BB,USA,...,No Deposit,240.0,0,Transient,153.00,1,0,Check-Out,2015-07-05,2015-07-03
66,Resort Hotel,0,3,0,2,2,0.0,0,BB,ESP,...,No Deposit,240.0,0,Transient,110.50,0,0,Check-Out,2015-07-05,2015-07-03
67,Resort Hotel,0,51,0,2,2,0.0,0,BB,POL,...,No Deposit,242.0,0,Transient,97.00,0,0,Check-Out,2015-07-05,2015-07-03
68,Resort Hotel,1,71,0,2,3,0.0,0,BB,PRT,...,No Deposit,242.0,0,Transient,110.30,0,2,Canceled,2015-06-16,2015-07-03
69,Resort Hotel,1,63,0,2,2,0.0,0,BB,PRT,...,No Deposit,240.0,0,Transient,82.00,0,2,Canceled,2015-06-18,2015-07-03
70,Resort Hotel,1,62,0,2,2,0.0,0,BB,PRT,...,No Deposit,240.0,0,Transient,97.00,0,1,Canceled,2015-07-03,2015-07-03

In [28]:
df["children"].fillna(0.0,inplace=True)
df

,hotel,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date
3,Resort Hotel,0,13,0,1,1,0.0,0,BB,GBR,...,No Deposit,304.0,0,Transient,75.00,0,0,Check-Out,2015-07-02,2015-07-01
4,Resort Hotel,0,14,0,2,2,0.0,0,BB,GBR,...,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03,2015-07-01
5,Resort Hotel,0,14,0,2,2,0.0,0,BB,GBR,...,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03,2015-07-01
7,Resort Hotel,0,9,0,2,2,0.0,0,FB,PRT,...,No Deposit,303.0,0,Transient,103.00,0,1,Check-Out,2015-07-03,2015-07-01
8,Resort Hotel,1,85,0,3,2,0.0,0,BB,PRT,...,No Deposit,240.0,0,Transient,82.00,0,1,Canceled,2015-05-06,2015-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2,5,2,0.0,0,BB,BEL,...,No Deposit,394.0,0,Transient,96.14,0,0,Check-Out,2017-09-06,2017-08-30
119386,City Hotel,0,102,2,5,3,0.0,0,BB,FRA,...,No Deposit,9.0,0,Transient,225.43,0,2,Check-Out,2017-09-07,2017-08-31
119387,City Hotel,0,34,2,5,2,0.0,0,BB,DEU,...,No Deposit,9.0,0,Transient,157.71,0,4,Check-Out,2017-09-07,2017-08-31
119388,City Hotel,0,109,2,5,2,0.0,0,BB,GBR,...,No Deposit,89.0,0,Transient,104.40,0,0,Check-Out,2017-09-07,2017-08-31
119389,City Hotel,0,205,2,7,2,0.0,0,HB,DEU,...,No Deposit,9.0,0,Transient,151.20,0,2,Check-Out,2017-09-07,2017-08-29

In [29]:
df.isnull().sum()

hotel                               0
is_canceled                         0
lead_time                           0
stays_in_weekend_nights             0
stays_in_week_nights                0
adults                              0
children                            0
babies                              0
meal                                0
country                           154
market_segment                      0
distribution_channel                0
is_repeated_guest                   0
previous_cancellations              0
previous_bookings_not_canceled      0
reserved_room_type                  0
assigned_room_type                  0
booking_changes                     0
deposit_type                        0
agent                               0
days_in_waiting_list                0
customer_type                       0
adr                                 0
required_car_parking_spaces         0
total_of_special_requests           0
reservation_status                  0
reservation_status_date             0
arrival_date                        0
dtype: int64

In [30]:
df["country"].fillna(method="ffill",inplace=True)

In [32]:
df.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
arrival_date                      0
dtype: int64